# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      configuration: "Release",
      export_method: "development",
      skip_codesigning: true,
      build_path: "./build",
      archive_path: "./build/Runner.xcarchive"
    )
  end
  
  desc "Build for physical device"
  lane :device do
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      configuration: "Debug",
      sdk: "iphoneos",
      destination: "generic/platform=iOS",
      skip_codesigning: true,
      skip_package_ipa: true
    )
  end
end
